const CREATE_BUSSINESS = "CREATE_BUSSINESS";
const LOGIN_ACTION = "LOGIN_ACTION";
const LOAD_BUSSINESS_SUCCESS = "LOAD_BUSSINESS_SUCCESS";
const GET_REVIEWS_AND_RATING = "GET_REVIEWS_AND_RATING";
const LOADING_ACTION_START = "LOADING_ACTION_START";
const LOADING_ACTION_END = "LOADING_ACTION_END";
const CHANGE_LOADING_STATE = "CHANGE_LOADING_STATE";
export {
  CREATE_BUSSINESS,
  LOGIN_ACTION,
  LOAD_BUSSINESS_SUCCESS,
  GET_REVIEWS_AND_RATING,
  LOADING_ACTION_START,
  LOADING_ACTION_END,
  CHANGE_LOADING_STATE,
};
